apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: tj1cgkiei-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/tj1cgkiei-java-springboot-gitops